### ISSUE TITLE
Unable to download if content_type is null

### ISSUE THREAD

**Issue by stee-ift** [luigifab/redmine-apijs#2]
Thank you & I love this plugin so much! I wonder if I can give my feedback here but I have no other way to go.
Redmine seems to set content_type to null when it's unable to determine the MIME type of the uploaded file. When users try to download this kind of file, they will encounter 500 internal error. The error looks like:

> Sent file /redmine-4.1.1/files/2021/10/211014091631_test_file.lic (0.3ms)
> Completed 500 Internal Server Error in 41ms (ActiveRecord: 29.5ms)
>   
> ArgumentError (:type option required):

I checked the code and find ApijsController is actually derived from Redmine's AttachmentsController, which make things easier.
I did a real quick workaround to avoid this error but wonder if it has any side effects. In ApijsController#download, Line 271:
replace `type: @attachment.content_type` with `type: detect_content_type(@attachment)`
The `detect_content_type` method from AttachmentsController will return 'application/octet-stream' if content_type is null.

Please let me know what you think, or I should use pull request, thank you.

**Comment by luigifab** [comment]
Thank you. I will test your change and check if `content_type` is used elsewhere.
I will add the fix to the next release.

**Comment by luigifab** [comment]
Added with v6.8.3.
